# Generated by Django 3.2.7 on 2021-10-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('first_call_time', models.CharField(max_length=5)),
                ('total_talk_time', models.CharField(max_length=5)),
                ('created_date', models.DateTimeField()),
            ],
        ),
    ]
