# Generated by Django 3.2.13 on 2022-12-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30)),
                ('account_pass', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('first_call_time', models.CharField(max_length=20)),
                ('total_talk_time', models.CharField(max_length=20)),
                ('call_date_time', models.DateTimeField(null=True)),
                ('initial_lead_date_time', models.DateTimeField(null=True)),
                ('won_job_date_time', models.DateTimeField(null=True)),
                ('job_fee', models.CharField(max_length=10, null=True)),
                ('run_date', models.DateField()),
                ('created_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('prelude', models.CharField(max_length=500)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
