# Generated by Django 3.2.7 on 2021-10-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_account_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='run_date',
            field=models.DateField(default='2021-10-26'),
            preserve_default=False,
        ),
    ]
