# Generated by Django 3.2.7 on 2021-10-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_run_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='call_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
