# Generated by Django 3.2.7 on 2021-10-27 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_lead_initial_lead_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='password',
            new_name='account_pass',
        ),
    ]
